# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aacac729b0f0cac3f330a4c797544432a7f092336979fa7ffacb2e197e8042b3f3267ddb8c332f714455dca71f6e9177fcb3b4e9d97367c079064a63553a9bfe

test:
  secret_key_base: bd8567daeb79b37489d26fff1df385e5aa4c78da6d75a24042c91022075175584a51eba0f5a342e39c367f844d7c1bc47228197a49b64fd18e159b4d9f9625f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
